NDefines.NCountry.MONARCH_MIN_SKILL = 0
NDefines.NCountry.MONARCH_MAX_SKILL = 9
NDefines.NCountry.ELECTIVE_LOCAL_MONARCH_MIN_BONUS = 1
NDefines.NCountry.ELECTIVE_LOCAL_MONARCH_MAX_BONUS = 3
NDefines.NCountry.ELECTIVE_FOREIGN_MONARCH_MIN_BONUS = 0
NDefines.NCountry.ELECTIVE_FOREIGN_MONARCH_MAX_BONUS = 0