NDefines.NCountry.PIETY_INCREASE_AT_GOOD_WAR = 0.05
NDefines.NCountry.PIETY_DECREASE_AT_BAD_WAR = -0.05
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0.05
NDefines.NCountry.ALLOW_ZERO_BASE_VALUES = 1