NDefines.NAI.BIGSHIP_FRACTION=0.25
NDefines.NEconomy.HEAVY_SHIP_MAINT_FACTOR = 0.03
NDefines.NMilitary.SAILOR_MAINTAINANCE = 0.005
NDefines.NEconomy.LIGHT_SHIP_MAINT_FACTOR = 0.02				
NDefines.NEconomy.GALLEY_MAINT_FACTOR = 0.025					
NDefines.NEconomy.TRANSPORT_MAINT_FACTOR = 0.025
NDefines.NMilitary.HEAVY_SHIP_COMBAT_WIDTH = 1
NDefines.NMilitary.LIGHT_SHIP_COMBAT_WIDTH = 0.5
NDefines.NMilitary.GALLEY_COMBAT_WIDTH = 0.5
NDefines.NMilitary.TRANSPORT_COMBAT_WIDTH = 0.5




NDefines.NMilitary.LEADER_MAX_PIPS = 9